### ISSUE TITLE
APK Download

### ISSUE THREAD

**Issue by IzzySoft** [tananaev/cell-tower-radar#7]
Hi Anton, could you make the APK available for download here? As you most likely know, there are those of us without access to Play Store's walled garden who would appreciate that. Thanks in advance!

**Comment by tananaev** [comment]
This app uses Google Maps, so I don't think you can use it without Google Services.

**Comment by IzzySoft** [comment]
If I may correct you: it is possible, e.g. using microG. And even if it were not, using GMaps does not require a Google account or access to Play Store. So may I ask you to re-consider?

**Comment by tananaev** [comment]
I'll think about it.

**Comment by IzzySoft** [comment]
Please let me know when you decide "pro". Thanks in advance!

**Comment by IzzySoft** [comment]
So any decision yet?
