### ISSUE TITLE
Switch to beacondb.net

### ISSUE THREAD

**Issue by Marhasp** [tananaev/cell-tower-radar#8]
Hello,

Mozilla has discontinued its localization service.
Would it be possible to switch to beacondb.net?
The API is identical to MLS.

https://beacondb.net/

Thank you

**Comment by tananaev** [comment]
Actually decided to go with OpenCelliD. But thanks for pointing out that we need to migrate off MLS.

**Comment by Marhasp** [comment]
Thank you.
I have another question. Is it possible to change the url to https? 
```kt
val url = "http://opencellid.org/cell/get?key=${key}&mcc=${mcc}&mnc=${mnc}&lac=${lac}&cellid=${cid}&format=json
```
